### ISSUE TITLE
Build fails with 'cannot resolve' dependancies error cause by inaccessible nexus repo

### ISSUE THREAD

**Issue by ender1975** [SIVECO/Palette#1]
Build fails because the nexus repo as defined in gradle.properites is inaccessible:
http://nexus/content/repositories/elearning-releases/

Gradle errors:

>  Could not resolve ro.siveco.ael:ael-cr-common:7.0.0-SNAPSHOT.
  Required by:
      project :
   > Could not resolve ro.siveco.ael:ael-cr-common:7.0.0-SNAPSHOT.
      > Unable to load Maven meta-data from http://nexus/content/repositories/elearning-releases/ro/siveco/ael/ael-cr-common/7.0.0-SNAPSHOT/maven-metadata.xml.
         > Could not get resource 'http://nexus/content/repositories/elearning-releases/ro/siveco/ael/ael-cr-common/7.0.0-SNAPSHOT/maven-metadata.xml'.
            > Could not GET 'http://nexus/content/repositories/elearning-releases/ro/siveco/ael/ael-cr-common/7.0.0-SNAPSHOT/maven-metadata.xml'.
               > nexus
> Could not resolve ro.siveco.ael:ael-cr-client:7.0.0-SNAPSHOT.
  Required by:
      project :
   > Could not resolve ro.siveco.ael:ael-cr-client:7.0.0-SNAPSHOT.
      > Unable to load Maven meta-data from http://nexus/content/repositories/elearning-releases/ro/siveco/ael/ael-cr-client/7.0.0-SNAPSHOT/maven-metadata.xml.
         > Could not get resource 'http://nexus/content/repositories/elearning-releases/ro/siveco/ael/ael-cr-client/7.0.0-SNAPSHOT/maven-metadata.xml'.
            > Could not GET 'http://nexus/content/repositories/elearning-releases/ro/siveco/ael/ael-cr-client/7.0.0-SNAPSHOT/maven-metadata.xml'.
               > nexus
> Could not resolve ro.siveco.ael.ims:ims-sqti:7.0.0-SNAPSHOT.
  Required by:
      project :
   > Could not resolve ro.siveco.ael.ims:ims-sqti:7.0.0-SNAPSHOT.
      > Unable to load Maven meta-data from http://nexus/content/repositories/elearning-releases/ro/siveco/ael/ims/ims-sqti/7.0.0-SNAPSHOT/maven-metadata.xml.
         > Could not get resource 'http://nexus/content/repositories/elearning-releases/ro/siveco/ael/ims/ims-sqti/7.0.0-SNAPSHOT/maven-metadata.xml'.
            > Could not GET 'http://nexus/content/repositories/elearning-releases/ro/siveco/ael/ims/ims-sqti/7.0.0-SNAPSHOT/maven-metadata.xml'.
               > nexus
> Could not resolve ro.siveco.ael.ims:ims-rte:7.0.0-SNAPSHOT.
  Required by:
      project :
   > Could not resolve ro.siveco.ael.ims:ims-rte:7.0.0-SNAPSHOT.
      > Unable to load Maven meta-data from http://nexus/content/repositories/elearning-releases/ro/siveco/ael/ims/ims-rte/7.0.0-SNAPSHOT/maven-metadata.xml.
         > Could not get resource 'http://nexus/content/repositories/elearning-releases/ro/siveco/ael/ims/ims-rte/7.0.0-SNAPSHOT/maven-metadata.xml'.
            > Could not GET 'http://nexus/content/repositories/elearning-releases/ro/siveco/ael/ims/ims-rte/7.0.0-SNAPSHOT/maven-metadata.xml'.
               > nexus
> Could not resolve ro.siveco.ael.xapi:ael-xapi-model:1.0.3.
  Required by:
      project :
   > Could not resolve ro.siveco.ael.xapi:ael-xapi-model:1.0.3.
      > Could not get resource 'http://nexus/content/repositories/elearning-releases/ro/siveco/ael/xapi/ael-xapi-model/1.0.3/ael-xapi-model-1.0.3.pom'.
         > Could not GET 'http://nexus/content/repositories/elearning-releases/ro/siveco/ael/xapi/ael-xapi-model/1.0.3/ael-xapi-model-1.0.3.pom'.
            > nexus
> Could not resolve ro.siveco.ram:ram:2.0.0-RC25.
  Required by:
      project :
   > Could not resolve ro.siveco.ram:ram:2.0.0-RC25.
      > Could not get resource 'http://nexus/content/repositories/elearning-releases/ro/siveco/ram/ram/2.0.0-RC25/ram-2.0.0-RC25.pom'.
         > Could not GET 'http://nexus/content/repositories/elearning-releases/ro/siveco/ram/ram/2.0.0-RC25/ram-2.0.0-RC25.pom'.
            > nexus
> Could not resolve org.olap4j:olap4j:0.9.7.309-JS-3.
  Required by:
      project : > net.sf.jasperreports:jasperreports:6.4.1
   > Could not resolve org.olap4j:olap4j:0.9.7.309-JS-3.
      > Could not get resource 'http://nexus/content/repositories/elearning-releases/org/olap4j/olap4j/0.9.7.309-JS-3/olap4j-0.9.7.309-JS-3.pom'.
         > Could not GET 'http://nexus/content/repositories/elearning-releases/org/olap4j/olap4j/0.9.7.309-JS-3/olap4j-0.9.7.309-JS-3.pom'.
            > nexus

**Comment by ender1975** [comment]
After I had a look at our _build.gradle_, there are some comments relating to „No Nexus access” and „Nexus access”. Basically some dependencies should be uncommented for no Nexus access and some should be commented. After doing that I’m only having a problem with the following:

> Could not find org.olap4j:olap4j:0.9.7.309-JS-3.
  Required by:
      project : > net.sf.jasperreports:jasperreports:6.4.1


This is for the case where I also comment out the Nexus repo. If the Nexus repo is uncommented, Gradle tries to look for this dependency there. I’m not sure why it’s not seeing the above lib in the libs folder, where it is located as well.

**Comment by ender1975** [comment]
Ok, I managed to resolve the OLAP4J problem by modifying build.gradle:

```
 compile("net.sf.jasperreports:jasperreports:6.4.1"){
        exclude group: 'org.olap4j', module: 'olap4j'
  }
```

But now I'm getting compilations errors where all the Siveco custom libraries are missing,  so I assume all the Siveco libraries listed above should be added to the libs folder.


> /Users/maciejb/Development/Palette/Palette/src/main/java/ro/siveco/ael/lcms/domain/taxonomies/service/CompetenceService.java:19: error: cannot find symbol
> import ro.siveco.ram.service.TreeEntityService;
>                             ^
>   symbol:   class TreeEntityService
>   location: package ro.siveco.ram.service
> /Users/maciejb/Development/Palette/Palette/src/main/java/ro/siveco/ael/lcms/domain/taxonomies/service/CompetenceService.java:27: error: cannot find symbol
> public class CompetenceService extends BaseEntityService<Competence> implements TreeEntityService<Competence, Long> {
>                                                                                 ^
>   symbol: class TreeEntityService
> /Users/maciejb/Development/Palette/Palette/src/main/java/ro/siveco/ael/service/lrs/LrsService.java:18: error: package ro.siveco.ael.xapi.model does not exist
> import ro.siveco.ael.xapi.model.Statement;
>                                ^
> /Users/maciejb/Development/Palette/Palette/src/main/java/ro/siveco/ael/service/lrs/LrsService.java:19: error: package ro.siveco.ael.xapi.model does not exist
> import ro.siveco.ael.xapi.model.StatementResult;
>                                ^
> /Users/maciejb/Development/Palette/Palette/src/main/java/ro/siveco/ael/service/lrs/LrsService.java:51: error: cannot find symbol
>     public List<Statement> getStatements(Map queryParams) throws Exception {
>                 ^
>   symbol:   class Statement
>   location: class LrsService
> /Users/maciejb/Development/Palette/Palette/src/main/java/ro/siveco/ael/service/lrs/LrsService.java:143: error: cannot find symbol
>     public List<Statement> getStatementsByActivityAndVerb(String activityId,
>                 ^
>   symbol:   class Statement
>   location: class LrsService
> /Users/maciejb/Development/Palette/Palette/src/main/java/ro/siveco/ael/service/lrs/LrsService.java:155: error: cannot find symbol
>     public List<Statement> getStatementsByUserAndParentActivityAndVerb(String userId, String parentActivityId,
>                 ^
>   symbol:   class Statement
>   location: class LrsService
> /Users/maciejb/Development/Palette/Palette/src/main/java/ro/siveco/ael/lcms/domain/course/model/Course.java:243: error: cannot find symbol
>             embeddedPropertyModel = true)
>                                     ^
>   symbol:   method embeddedPropertyModel()
>   location: @interface PropertyViewDescriptor
> 8 errors
>

**Comment by ender1975** [comment]
Just to some up, these I think are the missing Siveco dependencies:

```
- ro.siveco.ael:ael-cr-common:7.0.0-SNAPSHOT
- ro.siveco.ael:ael-cr-client:7.0.0-SNAPSHOT
- ro.siveco.ael.ims:ims-sqti:7.0.0-SNAPSHOT
- ro.siveco.ael.ims:ims-rte:7.0.0-SNAPSHOT
- ro.siveco.ael.xapi:ael-xapi-model:1.0.3
- ro.siveco.ram:ram:2.0.0-RC25
```

**Comment by diananiculescu** [comment]
only this dependency is needed and it needs to be added on the local repository

**Comment by ender1975** [comment]
Resolved by adding ro.siveco.ram to the libs folder and removing it from dependency list and also by removing the nexus repo.
